### ISSUE TITLE
search issue

### ISSUE THREAD

**Issue by gerasoul** [gjamuar/musicreco#1]
1.search for an artist   say Selena Gomez
2. select  related artists for selena gomez
3.click Show Selected Songs

A PHP Error was encountered

Severity: Notice

Message: Undefined variable: query_string

Filename: views/songs_view.php

Line Number: 303

Show selected songs
Genres Open
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: oldstate

Filename: views/songs_view.php

Line Number: 692

**Comment by gjamuar** [comment]
fixed. Select all songs in albums needs new development.
